name: Build and Push Release Image by Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push-stable-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Extract build args
        id: extract_tag
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: callmemhz
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            callmemhz/nexa:${{ steps.extract_tag.outputs.tag }}
            callmemhz/nexa:latest
